#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  scripts/audit-diff.sh <old-prefix> <new-prefix>

Example:
  scripts/audit-diff.sh \
    .migration-audit/20260222-002833 \
    .migration-audit/20260225-101500

Each prefix must have files generated by scripts/migration-baseline-audit.sh:
  <prefix>.system.txt
  <prefix>.units.txt
  <prefix>.identity.txt
  <prefix>.dns.txt
  <prefix>.hardware.txt
  <prefix>.session-services.txt
EOF
}

force=0
if [ "${1:-}" = "--force" ]; then
  force=1
  shift
fi

if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ] || [ "$#" -ne 2 ]; then
  usage
  exit 1
fi

old="$1"
new="$2"

require_file() {
  local f="$1"
  [ -f "$f" ] || { echo "[audit-diff] missing file: $f" >&2; exit 1; }
}

for suffix in system units identity dns hardware session-services; do
  require_file "${old}.${suffix}.txt"
  require_file "${new}.${suffix}.txt"
done

extract_version() {
  local f="$1"
  sed -n '1s/^# format-version: //p' "$f"
}

old_version="$(extract_version "${old}.system.txt")"
new_version="$(extract_version "${new}.system.txt")"
if [ -z "$old_version" ]; then old_version="1"; fi
if [ -z "$new_version" ]; then new_version="1"; fi

if [ "$old_version" != "$new_version" ] && [ "$force" -ne 1 ]; then
  echo "[audit-diff] format-version mismatch: old=$old_version new=$new_version" >&2
  echo "[audit-diff] rerun with --force to compare anyway" >&2
  exit 1
fi

report_dir=".migration-audit"
mkdir -p "$report_dir"
ts="$(date +%Y%m%d-%H%M%S)"
report="$report_dir/audit-diff-$ts.txt"

{
  echo "# Audit Diff Report"
  echo "old=$old"
  echo "new=$new"
  echo "format_version_old=$old_version"
  echo "format_version_new=$new_version"
  echo

  for suffix in system units identity dns hardware session-services; do
    echo "## ${suffix}"
    if diff -u "${old}.${suffix}.txt" "${new}.${suffix}.txt"; then
      echo "[same]"
    fi
    echo
  done
} >"$report"

echo "[audit-diff] report written: $report"
