music_directory         "~/Music"
playlist_directory      "~/.config/mpd/playlists"
db_file                 "~/.local/state/mpd/database"
log_file                "~/.local/state/mpd/log"
pid_file                "~/.local/state/mpd/pid"
state_file              "~/.local/state/mpd/state"
sticker_file            "~/.local/state/mpd/sticker.sql"

auto_update             "yes"
restore_paused          "yes"

#bind_to_address         "127.0.0.1"
bind_to_address "/tmp/mpd_socket"

#port                    "6600"

audio_output {
    type                "pipewire"
    name                "PipeWire Output"
}
